N=1

Vagrant.configure("2") do |config|
  (1..N).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "generic/debian9"
      node.vm.network "public_network", ip: "192.168.1.#{i + 135}", :name => 'vboxnet0', :adapter => 2
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
        vb.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet0"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.customize ["modifyvm", :id, "--macaddress2", "080027f8468#{i}"]    
      end

      node.vm.provision "ansible" do |ansible|
        ansible.verbose = "vvv"
        ansible.playbook = "kafka_zookeeper_install.yml"   
      end
    end      
  end  
end
