---
- hosts: server1
  remote_user: ss

  tasks:
  - name: import taskt to add virtualbox repo
    import_tasks: ./tasks/add_virtualBox_repo.yml

  - name: apt-get update
    apt:
      update_cache: yes
    become: yes
    become_method: su
    become_user: root

  - name: install basic configuration
    apt:
      name: ['virtualbox-5.2', 'vagrant', 'ansible', 'python3-pip', 'linux-headers-{{ ansible_kernel }}']
      state: present
    become: yes
    become_method: su
    become_user: root

  - name: add rights to user ss
    shell: gpasswd -a ss vboxusers
    become: yes
    become_method: su
    become_user: root

  - name: import taskt to install and configure vagrant task (install scilla)
    import_tasks: ./tasks/vagrant_configuration.yml
    
