
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"

  config.vm.define "scylla_db" do |continuous_integration|
    config.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "scyllaDB_inventory"
      ansible.verbose = "v"
      ansible.playbook = "scyllaDB_install.yml"
    end
  end
  
end
